"""change services to list

Revision ID: 1561ad9e0fd3
Revises: 3e2ab3e584b3
Create Date: 2025-12-29 21:24:23.039741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1561ad9e0fd3'
down_revision: Union[str, Sequence[str], None] = '3e2ab3e584b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_centers_email'), 'centers', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centers_email'), table_name='centers')
    # ### end Alembic commands ###
