"""init_db

Revision ID: 3e2ab3e584b3
Revises: 
Create Date: 2025-12-29 16:44:20.680316

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e2ab3e584b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tokens_valid_from_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('centers',
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('landmark', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clinic_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_map_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centers_contact'), 'centers', ['contact'], unique=False)
    op.create_index(op.f('ix_centers_district'), 'centers', ['district'], unique=False)
    op.create_index(op.f('ix_centers_id'), 'centers', ['id'], unique=False)
    op.create_index(op.f('ix_centers_landmark'), 'centers', ['landmark'], unique=False)
    op.create_index(op.f('ix_centers_location'), 'centers', ['location'], unique=False)
    op.create_index(op.f('ix_centers_name'), 'centers', ['name'], unique=False)
    op.create_index(op.f('ix_centers_pincode'), 'centers', ['pincode'], unique=False)
    op.create_index(op.f('ix_centers_user_id'), 'centers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centers_user_id'), table_name='centers')
    op.drop_index(op.f('ix_centers_pincode'), table_name='centers')
    op.drop_index(op.f('ix_centers_name'), table_name='centers')
    op.drop_index(op.f('ix_centers_location'), table_name='centers')
    op.drop_index(op.f('ix_centers_landmark'), table_name='centers')
    op.drop_index(op.f('ix_centers_id'), table_name='centers')
    op.drop_index(op.f('ix_centers_district'), table_name='centers')
    op.drop_index(op.f('ix_centers_contact'), table_name='centers')
    op.drop_table('centers')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
